"""
Patcht sync_runner.py:
1. Gruppierung auf 15-Minuten-Fenster
2. Encounter-Suche auf ±15 Minuten
3. Encounter period.end auf +15 Minuten
"""
from pathlib import Path

path = Path("sync_runner.py")
content = path.read_text(encoding="utf-8")
original = content

# --- Patch 1: Encounter-Suche auf 15-Minuten-Fenster ---
old1 = (
    '    timestamp_str = effective_dt.strftime("%Y-%m-%dT%H:%M:%SZ")\n'
    '\n'
    '    try:\n'
    '        payload = http_get_json(\n'
    '            f"{base_url}/Encounter",\n'
    '            auth,\n'
    '            params=[\n'
    '                ("subject", f"Patient/{patient_id}"),\n'
    '                ("date", f"eq{timestamp_str}"),   # exakter Sekundenmatch\n'
    '                ("_count", "10"),\n'
    '            ],\n'
    '        )\n'
    '        for resource in iter_resources(payload):\n'
    '            if resource.get("resourceType") != "Encounter":\n'
    '                continue\n'
    '            enc_id = str(resource.get("id") or "").strip()\n'
    '            if not enc_id:\n'
    '                continue\n'
    '            # period.start exakt prüfen (Sekunden-Präfix reicht)\n'
    '            period_start = str((resource.get("period") or {}).get("start") or "")\n'
    '            if period_start[:19] == timestamp_str[:19]:\n'
    '                print(f"[INFO] Encounter gefunden: {enc_id} für Patient {patient_id} um {timestamp_str}")\n'
    '                return f"Encounter/{enc_id}"\n'
    '    except RuntimeError as exc:\n'
    '        print(f"[WARN] Encounter-Suche fehlgeschlagen: {exc}")'
)
new1 = (
    '    timestamp_str = effective_dt.strftime("%Y-%m-%dT%H:%M:%SZ")\n'
    '    # Suchfenster: ±15 Minuten um den frühesten Messzeitpunkt der Gruppe\n'
    '    window_start = (effective_dt - timedelta(minutes=15)).strftime("%Y-%m-%dT%H:%M:%SZ")\n'
    '    window_end   = (effective_dt + timedelta(minutes=15)).strftime("%Y-%m-%dT%H:%M:%SZ")\n'
    '\n'
    '    try:\n'
    '        payload = http_get_json(\n'
    '            f"{base_url}/Encounter",\n'
    '            auth,\n'
    '            params=[\n'
    '                ("subject", f"Patient/{patient_id}"),\n'
    '                ("date", f"ge{window_start}"),\n'
    '                ("date", f"le{window_end}"),\n'
    '                ("_count", "10"),\n'
    '            ],\n'
    '        )\n'
    '        for resource in iter_resources(payload):\n'
    '            if resource.get("resourceType") != "Encounter":\n'
    '                continue\n'
    '            enc_id = str(resource.get("id") or "").strip()\n'
    '            if not enc_id:\n'
    '                continue\n'
    '            # period.start muss innerhalb des 15-Minuten-Fensters liegen\n'
    '            period_start = str((resource.get("period") or {}).get("start") or "")\n'
    '            if period_start[:19] >= window_start[:19] and period_start[:19] <= window_end[:19]:\n'
    '                print(f"[INFO] Encounter gefunden: {enc_id} für Patient {patient_id} um {timestamp_str}")\n'
    '                return f"Encounter/{enc_id}"\n'
    '    except RuntimeError as exc:\n'
    '        print(f"[WARN] Encounter-Suche fehlgeschlagen: {exc}")'
)

# --- Patch 2: period.end auf +15 Minuten ---
old2 = (
    '        "period": {\n'
    '            "start": timestamp_str,\n'
    '            "end":   timestamp_str,\n'
    '        },'
)
new2 = (
    '        "period": {\n'
    '            "start": timestamp_str,\n'
    '            "end":   (effective_dt + timedelta(minutes=15)).strftime("%Y-%m-%dT%H:%M:%SZ"),\n'
    '        },'
)

# --- Patch 3: 15-Minuten-Gruppierung in _sync_patient ---
old3 = (
    '    # Cache: exakter Timestamp → Encounter-Ref\n'
    '    # Blutdruck-Komponenten teilen denselben effectiveDateTime → selber Encounter\n'
    '    encounter_cache: Dict[str, Optional[str]] = {}\n'
    '\n'
    '    for observation in observations:\n'
    '        stats["scanned"] += 1\n'
    '        if not observation_in_window(observation, from_time=from_time):\n'
    '            stats["skipped_by_filter"] += 1\n'
    '            continue\n'
    '\n'
    '        expanded = expand_observation_for_transfer(observation)\n'
    '\n'
    '        # Alle gültigen Items mit ihrem geparsten Timestamp sammeln\n'
    '        valid_items: List[Tuple[Dict[str, Any], datetime]] = []\n'
    '        for item in expanded:\n'
    '            if not has_observation_value(item):\n'
    '                continue\n'
    '            code = observation_transfer_code(item)\n'
    '            if settings.only_codes and (not code or code not in set(settings.only_codes)):\n'
    '                continue\n'
    '            effective_dt = extract_effective_datetime(item)\n'
    '            if not effective_dt:\n'
    '                stats["skipped_no_timestamp"] += 1\n'
    '                continue\n'
    '            parsed = parse_dt(effective_dt)\n'
    '            if not parsed:\n'
    '                stats["skipped_no_timestamp"] += 1\n'
    '                continue\n'
    '            valid_items.append((item, parsed))\n'
    '\n'
    '        if not valid_items:\n'
    '            stats["skipped_by_filter"] += 1\n'
    '            continue\n'
    '\n'
    '        # Encounter einmal pro exaktem Messzeitpunkt anlegen (gecacht)\n'
    '        ref_dt    = valid_items[0][1]\n'
    '        cache_key = ref_dt.strftime("%Y-%m-%dT%H:%M:%SZ")\n'
    '\n'
    '        if cache_key not in encounter_cache:\n'
    '            try:\n'
    '                enc_ref = find_or_create_encounter(\n'
    '                    settings.sensdoc_base,\n'
    '                    settings.sensdoc_auth,\n'
    '                    sensdoc_id,\n'
    '                    ref_dt,\n'
    '                    settings.dry_run,\n'
    '                )\n'
    '                encounter_cache[cache_key] = enc_ref\n'
    '                if enc_ref:\n'
    '                    stats["encounter_created"] += 1\n'
    '            except RuntimeError as exc:\n'
    '                print(f"[WARN] Encounter für {cache_key} fehlgeschlagen: {exc}")\n'
    '                encounter_cache[cache_key] = None\n'
    '\n'
    '        encounter_ref = encounter_cache[cache_key]\n'
    '\n'
    '        observation_ids:   List[str] = []\n'
    '        observation_codes: List[str] = []\n'
    '\n'
    '        for item, _ in valid_items:\n'
    '            target_obs = build_target_observation(\n'
    '                item, sensdoc_id, settings.source_identifier_system, settings\n'
    '            )\n'
    '            # Encounter-Referenz in Observation eintragen\n'
    '            if encounter_ref:\n'
    '                target_obs["encounter"] = {"reference": encounter_ref}'
)
new3 = (
    '    # Alle gültigen Observations mit Timestamp sammeln\n'
    '    # Gruppierung: Messungen innerhalb von 15 Minuten → ein gemeinsamer Encounter\n'
    '    GROUP_WINDOW_MINUTES = 15\n'
    '\n'
    '    def group_key_for(dt: datetime) -> str:\n'
    '        """Rundet auf 15-Minuten-Fenster: z.B. 07:52 und 07:58 → selbe Gruppe."""\n'
    '        slot = (dt.hour * 60 + dt.minute) // GROUP_WINDOW_MINUTES\n'
    '        return f"{dt.strftime(\'%Y-%m-%d\')}_{slot}"\n'
    '\n'
    '    # Schritt 1: alle validen Items sammeln und nach 15-Min-Gruppe sortieren\n'
    '    groups: Dict[str, List[Tuple[Dict[str, Any], datetime]]] = {}\n'
    '    for observation in observations:\n'
    '        stats["scanned"] += 1\n'
    '        if not observation_in_window(observation, from_time=from_time):\n'
    '            stats["skipped_by_filter"] += 1\n'
    '            continue\n'
    '\n'
    '        expanded = expand_observation_for_transfer(observation)\n'
    '        added = False\n'
    '        for item in expanded:\n'
    '            if not has_observation_value(item):\n'
    '                continue\n'
    '            code = observation_transfer_code(item)\n'
    '            if settings.only_codes and (not code or code not in set(settings.only_codes)):\n'
    '                continue\n'
    '            effective_dt = extract_effective_datetime(item)\n'
    '            if not effective_dt:\n'
    '                stats["skipped_no_timestamp"] += 1\n'
    '                continue\n'
    '            parsed = parse_dt(effective_dt)\n'
    '            if not parsed:\n'
    '                stats["skipped_no_timestamp"] += 1\n'
    '                continue\n'
    '            gkey = group_key_for(parsed)\n'
    '            groups.setdefault(gkey, []).append((item, parsed))\n'
    '            added = True\n'
    '        if not added:\n'
    '            stats["skipped_by_filter"] += 1\n'
    '\n'
    '    # Schritt 2: pro Gruppe einen Encounter anlegen\n'
    '    encounter_cache: Dict[str, Optional[str]] = {}\n'
    '\n'
    '    for gkey in sorted(groups.keys()):\n'
    '        group_items = groups[gkey]\n'
    '\n'
    '        # Frühester Timestamp der Gruppe als Encounter-Zeitpunkt\n'
    '        ref_dt = min(dt for _, dt in group_items)\n'
    '\n'
    '        if gkey not in encounter_cache:\n'
    '            try:\n'
    '                enc_ref = find_or_create_encounter(\n'
    '                    settings.sensdoc_base,\n'
    '                    settings.sensdoc_auth,\n'
    '                    sensdoc_id,\n'
    '                    ref_dt,\n'
    '                    settings.dry_run,\n'
    '                )\n'
    '                encounter_cache[gkey] = enc_ref\n'
    '                if enc_ref:\n'
    '                    stats["encounter_created"] += 1\n'
    '            except RuntimeError as exc:\n'
    '                print(f"[WARN] Encounter für {gkey} fehlgeschlagen: {exc}")\n'
    '                encounter_cache[gkey] = None\n'
    '\n'
    '        encounter_ref = encounter_cache[gkey]\n'
    '\n'
    '        observation_ids:   List[str] = []\n'
    '        observation_codes: List[str] = []\n'
    '\n'
    '        for item, _ in group_items:\n'
    '            target_obs = build_target_observation(\n'
    '                item, sensdoc_id, settings.source_identifier_system, settings\n'
    '            )\n'
    '            # Encounter-Referenz in Observation eintragen\n'
    '            if encounter_ref:\n'
    '                target_obs["encounter"] = {"reference": encounter_ref}'
)

patches = [(old1, new1, "Encounter-Suche 15min"), (old2, new2, "period.end +15min"), (old3, new3, "15min-Gruppierung")]
for old, new, name in patches:
    if old in content:
        content = content.replace(old, new)
        print(f"✓ Patch '{name}' erfolgreich")
    else:
        print(f"✗ Patch '{name}' NICHT gefunden - bereits gepatcht oder anderer Text")

if content != original:
    path.write_text(content, encoding="utf-8")
    print(f"\nDatei gespeichert ({content.count(chr(10))} Zeilen)")
else:
    print("\nKeine Änderungen vorgenommen")
