sensdoc:
  database:
    url: "http://194.163.128.215:4010"
  auth:
    user_env: "FHIR_USER_put"
    pass_env: "FHIR_PASS_put"
  resource:
    name: "Patient"

# config.yaml
# ✅ Fester Hashcode (nicht generieren!)
fixed_code: "HGR2B3DZ"

# ✅ Welche Patienten sollen betroffen sein?
filter:
  given: "HGR2B3DZ"
  family: "Marge"
  birthDate: "1964-10-15"

code_template: "{Darius}{Marge}{1964-10-15}"

# Optional: Format des Geburtsdatums (z. B. "YYYY-MM-DD")
birthdate_format: "1964-10-15"

# Optional: Welche Felder sollen verwendet werden?
fields:
  given: "given"
  family: "family"
  birthdate: "birthDate"

given_keys: []
patient_links: {}

dry_run: false